name: P

on:
    workflow_call:
        inputs:
            ref:
                type: string
                default: ""
    workflow_dispatch:

jobs:
    j:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  ref: ${{ inputs.ref }}
