name: P

on:
    workflow_call:
    workflow_dispatch:

jobs:
    j:
        runs-on: ubuntu-latest
        steps:
            - run: echo "a=${{ github.event.pull_request.merged }} b=${{ github.event.pull_request.head.ref }}"
